# Generated by Django 4.0.6 on 2022-07-24 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing', '0016_alter_cinema_phone_alter_showtime_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='showtime',
            name='status',
            field=models.IntegerField(choices=[(4, 'فروش بلیت بسته شد'), (3, 'بلیت تمام شده'), (5, 'فیلم پخش شد'), (2, 'در حال فروش بلیت'), (6, 'سانس لغو شد'), (1, 'فروش آغاز نشده است')]),
        ),
    ]
