# Generated by Django 4.0.6 on 2022-08-01 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing', '0018_cinema_image_movie_poster_alter_showtime_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cinema',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='cinema_images/', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='showtime',
            name='status',
            field=models.IntegerField(choices=[(2, 'در حال فروش بلیت'), (1, 'فروش آغاز نشده است'), (6, 'سانس لغو شد'), (5, 'فیلم پخش شد'), (3, 'بلیت تمام شده'), (4, 'فروش بلیت بسته شد')]),
        ),
    ]
